apiVersion: ldap.kubed.io/v1alpha1
kind: ServiceAccount
metadata:
  name: myapp
spec:
  baseDn: ou=services,dc=example
  mail: myapp@example.com
  posix:
    uidNumber: "1050"
    gidNumber: "2001"
  connectionSecret:
    namespace: myapp
    name: myapp-ldap-creds   # keys: username, password
